#include <stdio.h>
#include "emq_register.h"
#include "message_example1.h"
#include "hello.h"

/* get process flag func register */
EMQ_GETFLAG_DECLEAR
    MSG_EXAMPLE1_OPERATION_DEFINE
    HELLO_OPERATION_FLAG_DEFINE
EMQ_GETFLAG_END

/* req streamlize func register */
EMQ_MESSAGE_STREAMLIZE_REQ_DECLEAR
    MSG_EXAMPL1_STREAMLIZE_REQ_DEFINE
    HELLO_STREAMLIZE_REQ_DEFINE
EMQ_MESSAGE_STREAMLIZE_REQ_END

/* req restreamlize func register */
EMQ_MESSAGE_RESTREAMLIZE_REQ_DECLEAR
    MSG_EXAMPL1_RESTREAMLIZE_REQ_DEFINE
    HELLO_RESTREAMLIZE_REQ_DEFINE
EMQ_MESSAGE_RESTREAMLIZE_REQ_END

/* rep streamlize func register */
EMQ_MESSAGE_STREAMLIZE_REP_DECLEAR
    MSG_EXAMPL1_STREAMLIZE_REP_DEFINE 
    HELLO_STREAMLIZE_REP_DEFINE
EMQ_MESSAGE_STREAMLIZE_REP_END

/* rep restreamlize func register */
EMQ_MESSAGE_RESTREAMLIZE_REP_DECLEAR
    MSG_EXAMPL1_RESTREAMLIZE_REP_DEFINE
    HELLO_RESTREAMLIZE_REP_DEFINE
EMQ_MESSAGE_RESTREAMLIZE_REP_END

/* req callback func register */
EMQ_MESSAGE_REQ_CALLBACKFUNC_DECLEAR
    MSG_EXAMPL1_REQ_CALLBACKFUNC1_RDEFINE
    MSG_EXAMPL1_REQ_CALLBACKFUNC2_RDEFINE
    HELLO_REQ_CALLBACKFUNC1_RDEFINE
    HELLO_REQ_CALLBACKFUNC2_RDEFINE
EMQ_MESSAGE_REQ_CALLBACKFUNC_END

/* rep callback func register */
EMQ_MESSAGE_REP_CALLBACKFUNC_DECLEAR
    MSG_EXAMPL1_REP_CALLBACKFUNC1_RDEFINE
    MSG_EXAMPL1_REP_CALLBACKFUNC2_RDEFINE
    HELLO_REP_CALLBACKFUNC1_RDEFINE
    HELLO_REP_CALLBACKFUNC2_RDEFINE
EMQ_MESSAGE_REP_CALLBACKFUNC_END
