#ifndef _EMQ_REGISTER_INCLUDE
#define _EMQ_REGISTER_INCLUDE

#include "message.h"
#include "message_example1.h"

EMQ_GETFLAG_DECLEAR
    MSG_EXAMPLE1_OPERATION_DEFINE
EMQ_GETFLAG_END

EMQ_MESSAGE_STREAMLIZE_DECLEAR
    MSG_EXAMPL1_STREAMLIZE_DEFINE
EMQ_MESSAGE_STREAMLIZE_END

EMQ_MESSAGE_RESTREAMLIZE_DECLEAR
    MSG_EXAMPL1_RESTREAMLIZE_DEFINE
EMQ_MESSAGE_RESTREAMLIZE_END

#endif
